sudo: required

language: go

services:
  - docker

install:
  - echo "installing..."
  - curl -L https://aka.ms/InstallAzureCli | bash
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - docker pull golang:latest
  - docker pull alpine:latest

script:
  - echo "building..."
  - docker build -t shenacr.azurecr.io/gframe-oauth:latest -f ./services/oauth.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-reception:latest -f ./services/reception_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-broker:latest -f ./services/broker_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-notification:latest -f ./services/notification_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-admin:latest -f ./services/admin_svc.Dockerfile ./services

after_success:
  - echo "$DOCKER_PASSWORD" | docker login shenacr.azurecr.io -u "$DOCKER_USERNAME" --password-stdin
  - docker push shenacr.azurecr.io/gframe-oauth:latest
  - docker push shenacr.azurecr.io/gframe-reception:latest
  - docker push shenacr.azurecr.io/gframe-broker:latest
  - docker push shenacr.azurecr.io/gframe-notification:latest
  - docker push shenacr.azurecr.io/gframe-admin:latest
  
before_deploy:
  - az login -u "$AZ_USERNAME" -p "$AZ_PASSWORD"
  - az aks get-credentials --resource-group k8s --name "$AKS_NAME"
  
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
  
#notifications:
#  email:
#    on_failure: always
#    on_success: never