sudo: required

env:
  global:
    - VERSION_NUMBER="v0.$TRAVIS_BUILD_NUMBER"

language: go

services:
  - docker

install:
  - echo "installing..."
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
  - export AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-get update
  - sudo apt-get install azure-cli
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - docker pull golang:latest
  - docker pull alpine:latest
  - docker pull node:alpine

script:
  - echo "building with $VERSION_NUMBER..."
  - docker build -t shenacr.azurecr.io/gframe-oauth:$VERSION_NUMBER -f ./services/oauth.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-reception:$VERSION_NUMBER -f ./services/reception_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-broker:$VERSION_NUMBER -f ./services/broker_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-notification:$VERSION_NUMBER -f ./services/notification_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-admin:$VERSION_NUMBER -f ./services/admin_svc.Dockerfile ./services
  - docker build -t shenacr.azurecr.io/gframe-playercli:$VERSION_NUMBER -f ./clients/playercli/Dockerfile ./clients/playercli
  - docker build -t shenacr.azurecr.io/gframe-admincli:$VERSION_NUMBER -f ./clients/admincli/Dockerfile ./clients/admincli

after_success:
  - echo "$DOCKER_PASSWORD" | docker login shenacr.azurecr.io -u "$DOCKER_USERNAME" --password-stdin
  - docker push shenacr.azurecr.io/gframe-oauth:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-reception:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-broker:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-notification:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-admin:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-playercli:$VERSION_NUMBER
  - docker push shenacr.azurecr.io/gframe-admincli:$VERSION_NUMBER
  
before_deploy:
  - az login -u "$AZ_USERNAME" -p "$AZ_PASSWORD"
  - az aks get-credentials --resource-group k8s --name "$AKS_NAME"
  
deploy:
  provider: script
  script: bash deploy/deploy.sh $VERSION_NUMBER
  on:
    branch: master
  
#notifications:
#  email:
#    on_failure: always
#    on_success: never