invoke-expression 'cmd /c start powershell -Command { go run .\oauth }'
invoke-expression 'cmd /c start powershell -Command { go run .\broker_svc }'
invoke-expression 'cmd /c start powershell -Command { go run .\notification_svc }'
invoke-expression 'cmd /c start powershell -Command { go run .\reception_svc }'
invoke-expression 'cmd /c start powershell -Command { cd .\playercli; npm start }'
invoke-expression 'cmd /c start powershell -Command { cd .\admincli; npm start }'
invoke-expression 'cmd /c start powershell -Command { go run .\admin_notification_svc }'