apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: gframe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: shenacr.azurecr.io/gframe-game:{{VERSION_NUMBER}}
        env:
        - name: PORT
          value: "80"
        - name: JWT_KEY
          value: "00000000"
        - name: KAFKA_BROKERS
          value: "kafka-1:9092"
          #value: "kafka-1:9092 kafka-2:9092"
        - name: BROKER_RPC
          value: "broker:90"
        - name: REDIS_SERVER
          value: "redis:6379"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: gframe
  labels:
    app: game
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
  selector:
    app: game