apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: gframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth
        image: shenacr.azurecr.io/gframe-oauth:{{VERSION_NUMBER}}
        env:
        - name: PORT
          value: "80"
        - name: JWT_KEY
          value: "00000000"
        - name: AUTH_DOMAIN
          value: "https://www.gframe.fun"
        ports:
        - name: web
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  namespace: gframe
  labels:
    app: oauth
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
  selector:
    app: oauth
