apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception
  namespace: gframe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reception
  template:
    metadata:
      labels:
        app: reception
    spec:
      containers:
      - name: reception
        image: shenacr.azurecr.io/gframe-reception:{{VERSION_NUMBER}}
        env:
        - name: PORT
          value: "80"
        - name: JWT_KEY
          value: "00000000"
        - name: KAFKA_BROKERS
          value: "kafka-1:9092 kafka-2:9092"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: reception
  namespace: gframe
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: reception