// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package events

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReceptionResponse struct {
	Acknowledged         bool     `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceptionResponse) Reset()         { *m = ReceptionResponse{} }
func (m *ReceptionResponse) String() string { return proto.CompactTextString(m) }
func (*ReceptionResponse) ProtoMessage()    {}
func (*ReceptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ReceptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceptionResponse.Unmarshal(m, b)
}
func (m *ReceptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceptionResponse.Marshal(b, m, deterministic)
}
func (m *ReceptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceptionResponse.Merge(m, src)
}
func (m *ReceptionResponse) XXX_Size() int {
	return xxx_messageInfo_ReceptionResponse.Size(m)
}
func (m *ReceptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceptionResponse proto.InternalMessageInfo

func (m *ReceptionResponse) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "events.User")
	proto.RegisterType((*ReceptionResponse)(nil), "events.ReceptionResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0x56, 0xd2,
	0xe2, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x02, 0x8b, 0x80, 0xd9, 0x4a, 0xe6, 0x5c, 0x82, 0x41, 0xa9, 0xc9, 0xa9, 0x05, 0x25, 0x99, 0xf9,
	0x79, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x4a, 0x5c, 0x3c, 0x89, 0xc9, 0xd9,
	0x79, 0xf9, 0xe5, 0x39, 0xa9, 0x29, 0xe9, 0xa9, 0x10, 0x23, 0x38, 0x82, 0x50, 0xc4, 0x8c, 0x6a,
	0xb8, 0x78, 0x41, 0x96, 0xc0, 0x35, 0x0b, 0x99, 0x70, 0xb1, 0x3b, 0x67, 0xa4, 0x26, 0x67, 0x7b,
	0xe6, 0x09, 0xf1, 0xe8, 0x41, 0x5c, 0xa2, 0x07, 0x52, 0x21, 0x25, 0x09, 0xe3, 0x61, 0x58, 0xa4,
	0xc4, 0x20, 0x64, 0xca, 0xc5, 0x01, 0xd6, 0xe5, 0x5f, 0x5a, 0x42, 0x82, 0xb6, 0x24, 0x36, 0xb0,
	0x8f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xdd, 0xf5, 0xf7, 0xff, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserReceptionClient is the client API for UserReception service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserReceptionClient interface {
	// User checkin
	CheckIn(ctx context.Context, in *User, opts ...grpc.CallOption) (*ReceptionResponse, error)
	// User checkout
	CheckOut(ctx context.Context, in *User, opts ...grpc.CallOption) (*ReceptionResponse, error)
}

type userReceptionClient struct {
	cc *grpc.ClientConn
}

func NewUserReceptionClient(cc *grpc.ClientConn) UserReceptionClient {
	return &userReceptionClient{cc}
}

func (c *userReceptionClient) CheckIn(ctx context.Context, in *User, opts ...grpc.CallOption) (*ReceptionResponse, error) {
	out := new(ReceptionResponse)
	err := c.cc.Invoke(ctx, "/events.UserReception/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userReceptionClient) CheckOut(ctx context.Context, in *User, opts ...grpc.CallOption) (*ReceptionResponse, error) {
	out := new(ReceptionResponse)
	err := c.cc.Invoke(ctx, "/events.UserReception/CheckOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserReceptionServer is the server API for UserReception service.
type UserReceptionServer interface {
	// User checkin
	CheckIn(context.Context, *User) (*ReceptionResponse, error)
	// User checkout
	CheckOut(context.Context, *User) (*ReceptionResponse, error)
}

// UnimplementedUserReceptionServer can be embedded to have forward compatible implementations.
type UnimplementedUserReceptionServer struct {
}

func (*UnimplementedUserReceptionServer) CheckIn(ctx context.Context, req *User) (*ReceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIn not implemented")
}
func (*UnimplementedUserReceptionServer) CheckOut(ctx context.Context, req *User) (*ReceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOut not implemented")
}

func RegisterUserReceptionServer(s *grpc.Server, srv UserReceptionServer) {
	s.RegisterService(&_UserReception_serviceDesc, srv)
}

func _UserReception_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserReceptionServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.UserReception/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserReceptionServer).CheckIn(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserReception_CheckOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserReceptionServer).CheckOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.UserReception/CheckOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserReceptionServer).CheckOut(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserReception_serviceDesc = grpc.ServiceDesc{
	ServiceName: "events.UserReception",
	HandlerType: (*UserReceptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _UserReception_CheckIn_Handler,
		},
		{
			MethodName: "CheckOut",
			Handler:    _UserReception_CheckOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
