version: '3'
services:
  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "player:2:1"

  oauth_svc:
    build:
      context: .
      dockerfile: oauth.Dockerfile
    ports:
      - "8440:80"
    environment:
      - PORT=80
      - JWT_KEY=00000000
  reception_svc:
    build:
      context: .
      dockerfile: reception_svc.Dockerfile
    ports:
      - "8441:80"
    environment:
      - PORT=80
  broker_svc:
    build:
      context: .
      dockerfile: broker_svc.Dockerfile
    environment:
      - REDIS_SERVER=redis_db:6379
  notification_svc:
    build:
      context: .
      dockerfile: notification_svc.Dockerfile
    ports:
      - "8442:80"
    environment:
      - PORT=80
      - JWT_KEY=00000000
      - REDIS_SERVER=redis_db:6379
    
  admin_svc:
    build:
        context: .
        dockerfile: admin_svc.Dockerfile
    ports: 
      - "8451:80"
    environment:
      - PORT=80
      - REDIS_SERVER=redis_db:6379
      - RECEPTION_URL=http://reception_svc:80
      - OAUTH_URL=http://oauth_svc:80