version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  oauth:
    container_name: oauth_svc
    build:
      context: .
      dockerfile: oauth.Dockerfile
    ports:
      - "8440:80"
    environment:
      - PORT=80
      - JWT_KEY=00000000
  reception_svc:
    container_name: reception_svc
    build:
      context: .
      dockerfile: reception_svc.Dockerfile
    ports:
      - "8441:80"
    environment:
      - PORT=80
  broker_svc:
    container_name: broker_svc
    build:
      context: .
      dockerfile: broker_svc.Dockerfile
    environment:
      - REDIS_SERVER=redis:6379
  notification_svc:
    container_name: notification_svc
    build:
      context: .
      dockerfile: notification_svc.Dockerfile
    ports:
      - "8442:80"
    environment:
      - PORT=80
      - JWT_KEY=00000000
      - REDIS_SERVER=redis:6379
    
  admin_svc:
    container_name: admin_svc
    build:
        context: .
        dockerfile: admin_svc.Dockerfile
    ports: 
      - "8451:80"
    environment:
      - PORT=80
      - REDIS_SERVER=redis:6379
      - RECEPTION_URL=http://reception_svc:80
      - OAUTH_URL=http://oauth:80