apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: gframe
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: edentidus@foxmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}