apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1-deployment
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      infra: kafka-1
  template:
    metadata:
      labels:
        infra: kafka-1
    spec:
      containers:
      - name: kafka-1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(THIS_POD_IP)
        tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-svc
  namespace: infra
spec:
  type: ClusterIP
  selector:
    infra: kafka-1
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2-deployment
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      infra: kafka-2
  template:
    metadata:
      labels:
        infra: kafka-2
    spec:
      containers:
      - name: kafka-2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: $(THIS_POD_IP)
        tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-svc
  namespace: infra
spec:
  type: ClusterIP
  selector:
    infra: kafka-2
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092