apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
    - gframe
  endpoints:
  - port: web
    interval: 30s