coreDns:
  enabled: true

kubeDns:
  enabled: false

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  adminPassword: {{GrafanaPassword}}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.gframe.fun
    tls:
      - secretName: tls-secret
        hosts:
        - grafana.gframe.fun
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 10Gi