apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oauth
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels: 
      app: oauth
  namespaceSelector:
    matchNames:
    - gframe
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels: 
      app: admin
  namespaceSelector:
    matchNames:
    - gframe
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: broker
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels: 
      app: broker
  namespaceSelector:
    matchNames:
    - gframe
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: game
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels: 
      app: game
  namespaceSelector:
    matchNames:
    - gframe
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-backend
  namespace: monitoring
  labels:
    release: prometheus
  resources:
    requests:
      memory: 200Mi

