// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/enum.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_None EventType = 0
	EventType_In   EventType = 1
	EventType_Out  EventType = 2
	EventType_Play EventType = 3
)

var EventType_name = map[int32]string{
	0: "None",
	1: "In",
	2: "Out",
	3: "Play",
}

var EventType_value = map[string]int32{
	"None": 0,
	"In":   1,
	"Out":  2,
	"Play": 3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67f9a48cc0dd671e, []int{0}
}

func init() {
	proto.RegisterEnum("contracts.EventType", EventType_name, EventType_value)
}

func init() { proto.RegisterFile("contracts/enum.proto", fileDescriptor_67f9a48cc0dd671e) }

var fileDescriptor_67f9a48cc0dd671e = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0x29, 0xd6, 0x4f, 0xcd, 0x2b, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x84, 0x8b, 0x6a, 0x19, 0x70, 0x71, 0xba, 0x96, 0xa5, 0xe6, 0x95, 0x84, 0x54, 0x16,
	0xa4, 0x0a, 0x71, 0x70, 0xb1, 0xf8, 0xe5, 0xe7, 0xa5, 0x0a, 0x30, 0x08, 0xb1, 0x71, 0x31, 0x79,
	0xe6, 0x09, 0x30, 0x0a, 0xb1, 0x73, 0x31, 0xfb, 0x97, 0x96, 0x08, 0x30, 0x81, 0xa4, 0x02, 0x72,
	0x12, 0x2b, 0x05, 0x98, 0x93, 0xd8, 0xc0, 0x66, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x96,
	0x1a, 0x94, 0x99, 0x5b, 0x00, 0x00, 0x00,
}
