// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/group.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupInfo struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Players              []*User     `protobuf:"bytes,2,rep,name=Players,proto3" json:"Players,omitempty"`
	Status               GroupStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=contracts.GroupStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a525d655bb7247a5, []int{0}
}

func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (m *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(m, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

func (m *GroupInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GroupInfo) GetPlayers() []*User {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GroupInfo) GetStatus() GroupStatus {
	if m != nil {
		return m.Status
	}
	return GroupStatus_GroupNone
}

func init() {
	proto.RegisterType((*GroupInfo)(nil), "contracts.GroupInfo")
}

func init() { proto.RegisterFile("contracts/group.proto", fileDescriptor_a525d655bb7247a5) }

var fileDescriptor_a525d655bb7247a5 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0x29, 0xd6, 0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x4b, 0x89, 0x20, 0x54, 0xa4, 0xe6, 0x95, 0xe6, 0x42, 0x14, 0x20,
	0x8b, 0x96, 0x16, 0xa7, 0x16, 0x41, 0x44, 0x95, 0xca, 0xb8, 0x38, 0xdd, 0x41, 0xa6, 0x78, 0xe6,
	0xa5, 0xe5, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31,
	0x79, 0xba, 0x08, 0x69, 0x72, 0xb1, 0x07, 0xe4, 0x24, 0x56, 0xa6, 0x16, 0x15, 0x4b, 0x30, 0x29,
	0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xeb, 0xc1, 0x0d, 0xd1, 0x0b, 0x2d, 0x4e, 0x2d, 0x0a, 0x82, 0xc9,
	0x0b, 0xe9, 0x71, 0xb1, 0x05, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0xf0,
	0x19, 0x89, 0x21, 0xa9, 0x04, 0x5b, 0x00, 0x91, 0x0d, 0x82, 0xaa, 0x4a, 0x62, 0x03, 0x5b, 0x6f,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xe3, 0x2d, 0xfb, 0xce, 0x00, 0x00, 0x00,
}
