// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/play.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shape int32

const (
	Shape_ShapeNone Shape = 0
	Shape_Rock      Shape = 1
	Shape_Paper     Shape = 2
	Shape_Scissors  Shape = 3
)

var Shape_name = map[int32]string{
	0: "ShapeNone",
	1: "Rock",
	2: "Paper",
	3: "Scissors",
}

var Shape_value = map[string]int32{
	"ShapeNone": 0,
	"Rock":      1,
	"Paper":     2,
	"Scissors":  3,
}

func (x Shape) String() string {
	return proto.EnumName(Shape_name, int32(x))
}

func (Shape) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{0}
}

type Playing struct {
	Player               *User    `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Shape                Shape    `protobuf:"varint,2,opt,name=shape,proto3,enum=contracts.Shape" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Playing) Reset()         { *m = Playing{} }
func (m *Playing) String() string { return proto.CompactTextString(m) }
func (*Playing) ProtoMessage()    {}
func (*Playing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{0}
}

func (m *Playing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playing.Unmarshal(m, b)
}
func (m *Playing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playing.Marshal(b, m, deterministic)
}
func (m *Playing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playing.Merge(m, src)
}
func (m *Playing) XXX_Size() int {
	return xxx_messageInfo_Playing.Size(m)
}
func (m *Playing) XXX_DiscardUnknown() {
	xxx_messageInfo_Playing.DiscardUnknown(m)
}

var xxx_messageInfo_Playing proto.InternalMessageInfo

func (m *Playing) GetPlayer() *User {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *Playing) GetShape() Shape {
	if m != nil {
		return m.Shape
	}
	return Shape_ShapeNone
}

type GameEvent struct {
	Play                 *Playing   `protobuf:"bytes,1,opt,name=play,proto3" json:"play,omitempty"`
	Group                *GroupInfo `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Type                 EventType  `protobuf:"varint,3,opt,name=type,proto3,enum=contracts.EventType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GameEvent) Reset()         { *m = GameEvent{} }
func (m *GameEvent) String() string { return proto.CompactTextString(m) }
func (*GameEvent) ProtoMessage()    {}
func (*GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{1}
}

func (m *GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameEvent.Unmarshal(m, b)
}
func (m *GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameEvent.Marshal(b, m, deterministic)
}
func (m *GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameEvent.Merge(m, src)
}
func (m *GameEvent) XXX_Size() int {
	return xxx_messageInfo_GameEvent.Size(m)
}
func (m *GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameEvent proto.InternalMessageInfo

func (m *GameEvent) GetPlay() *Playing {
	if m != nil {
		return m.Play
	}
	return nil
}

func (m *GameEvent) GetGroup() *GroupInfo {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GameEvent) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EventNone
}

type Result struct {
	Plays                []*Playing `protobuf:"bytes,1,rep,name=plays,proto3" json:"plays,omitempty"`
	Winner               int32      `protobuf:"varint,2,opt,name=winner,proto3" json:"winner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetPlays() []*Playing {
	if m != nil {
		return m.Plays
	}
	return nil
}

func (m *Result) GetWinner() int32 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func init() {
	proto.RegisterEnum("contracts.Shape", Shape_name, Shape_value)
	proto.RegisterType((*Playing)(nil), "contracts.Playing")
	proto.RegisterType((*GameEvent)(nil), "contracts.GameEvent")
	proto.RegisterType((*Result)(nil), "contracts.Result")
}

func init() { proto.RegisterFile("contracts/play.proto", fileDescriptor_8b9dc4efa854592d) }

var fileDescriptor_8b9dc4efa854592d = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x49, 0x5b, 0x87, 0xe6, 0xca, 0x9f, 0xe8, 0x54, 0x50, 0xc4, 0x54, 0x75, 0x28, 0x51,
	0x87, 0x22, 0x95, 0x89, 0x07, 0x40, 0x15, 0x0c, 0xa8, 0x72, 0x61, 0x61, 0x33, 0xd1, 0x51, 0x2a,
	0x52, 0xdb, 0xb2, 0x1d, 0x50, 0x1e, 0x81, 0xb7, 0x46, 0x71, 0xa2, 0xe2, 0x85, 0xcd, 0xfe, 0xee,
	0xbb, 0xbb, 0x9f, 0x0d, 0xe3, 0x42, 0x49, 0x67, 0x44, 0xe1, 0xec, 0x8d, 0x2e, 0x45, 0xbd, 0xd0,
	0x46, 0x39, 0x85, 0xc9, 0x81, 0x5e, 0x05, 0x02, 0xc9, 0x6a, 0xdf, 0x0a, 0x21, 0xad, 0x2c, 0x99,
	0x8e, 0x5e, 0xfc, 0xd1, 0xad, 0x51, 0x95, 0x6e, 0xf1, 0xf4, 0x15, 0x8e, 0xd7, 0xa5, 0xa8, 0x77,
	0x72, 0x8b, 0xd7, 0x10, 0x37, 0x6b, 0xc8, 0x64, 0xd1, 0x24, 0xca, 0x47, 0xcb, 0xf3, 0xc5, 0xa1,
	0x65, 0xf1, 0x62, 0xc9, 0xf0, 0xae, 0x8c, 0x33, 0x60, 0xf6, 0x43, 0x68, 0xca, 0x7a, 0x93, 0x28,
	0x3f, 0x5b, 0xa6, 0x81, 0xb7, 0x69, 0x38, 0x6f, 0xcb, 0xd3, 0x9f, 0x08, 0x92, 0x95, 0xd8, 0xd3,
	0xfd, 0x17, 0x49, 0x87, 0x33, 0x18, 0x34, 0xfd, 0xdd, 0x70, 0x0c, 0x9a, 0xba, 0x00, 0xdc, 0xd7,
	0x71, 0x0e, 0xcc, 0x07, 0xf4, 0xd3, 0x47, 0xcb, 0x71, 0x20, 0xae, 0x1a, 0xfe, 0x20, 0xdf, 0x15,
	0x6f, 0x15, 0xcc, 0x61, 0xe0, 0x6a, 0x4d, 0x59, 0xdf, 0x07, 0x09, 0x55, 0xbf, 0xf3, 0xb9, 0xd6,
	0xc4, 0xbd, 0x31, 0x7d, 0x84, 0x98, 0x93, 0xad, 0x4a, 0x87, 0x39, 0xb0, 0x66, 0x8f, 0xcd, 0xa2,
	0x49, 0xff, 0x9f, 0x20, 0xad, 0x80, 0x97, 0x10, 0x7f, 0xef, 0xa4, 0x24, 0xe3, 0xa3, 0x30, 0xde,
	0xdd, 0xe6, 0x77, 0xc0, 0xfc, 0x3b, 0xf1, 0x14, 0x12, 0x7f, 0x78, 0x52, 0x92, 0xd2, 0x23, 0x1c,
	0xc2, 0x80, 0xab, 0xe2, 0x33, 0x8d, 0x30, 0x01, 0xb6, 0x16, 0x9a, 0x4c, 0xda, 0xc3, 0x13, 0x18,
	0x6e, 0x8a, 0x9d, 0xb5, 0xca, 0xd8, 0xb4, 0xff, 0x16, 0xfb, 0x5f, 0xbf, 0xfd, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xca, 0x31, 0xc3, 0x34, 0xdb, 0x01, 0x00, 0x00,
}
