// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/play.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Shape int32

const (
	Shape_ShapeNone Shape = 0
	Shape_Rock      Shape = 1
	Shape_Paper     Shape = 2
	Shape_Scissors  Shape = 3
)

var Shape_name = map[int32]string{
	0: "ShapeNone",
	1: "Rock",
	2: "Paper",
	3: "Scissors",
}

var Shape_value = map[string]int32{
	"ShapeNone": 0,
	"Rock":      1,
	"Paper":     2,
	"Scissors":  3,
}

func (x Shape) String() string {
	return proto.EnumName(Shape_name, int32(x))
}

func (Shape) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{0}
}

type Playing struct {
	Player               *User    `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Shape                Shape    `protobuf:"varint,2,opt,name=shape,proto3,enum=contracts.Shape" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Playing) Reset()         { *m = Playing{} }
func (m *Playing) String() string { return proto.CompactTextString(m) }
func (*Playing) ProtoMessage()    {}
func (*Playing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{0}
}

func (m *Playing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playing.Unmarshal(m, b)
}
func (m *Playing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playing.Marshal(b, m, deterministic)
}
func (m *Playing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playing.Merge(m, src)
}
func (m *Playing) XXX_Size() int {
	return xxx_messageInfo_Playing.Size(m)
}
func (m *Playing) XXX_DiscardUnknown() {
	xxx_messageInfo_Playing.DiscardUnknown(m)
}

var xxx_messageInfo_Playing proto.InternalMessageInfo

func (m *Playing) GetPlayer() *User {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *Playing) GetShape() Shape {
	if m != nil {
		return m.Shape
	}
	return Shape_ShapeNone
}

type Game struct {
	Play                 *Playing   `protobuf:"bytes,1,opt,name=play,proto3" json:"play,omitempty"`
	Group                *GroupInfo `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b9dc4efa854592d, []int{1}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetPlay() *Playing {
	if m != nil {
		return m.Play
	}
	return nil
}

func (m *Game) GetGroup() *GroupInfo {
	if m != nil {
		return m.Group
	}
	return nil
}

func init() {
	proto.RegisterEnum("contracts.Shape", Shape_name, Shape_value)
	proto.RegisterType((*Playing)(nil), "contracts.Playing")
	proto.RegisterType((*Game)(nil), "contracts.Game")
}

func init() { proto.RegisterFile("contracts/play.proto", fileDescriptor_8b9dc4efa854592d) }

var fileDescriptor_8b9dc4efa854592d = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0x86, 0x5d, 0xdc, 0x45, 0x76, 0xf0, 0xa3, 0x99, 0x60, 0x42, 0x38, 0x11, 0x0e, 0x48, 0x38,
	0xac, 0xc9, 0x7a, 0xf2, 0x17, 0x10, 0x2f, 0x86, 0x94, 0x78, 0xe1, 0x56, 0x37, 0x15, 0x89, 0xd8,
	0x69, 0xa6, 0xcb, 0x81, 0x7f, 0x6f, 0xda, 0x6e, 0xd6, 0xde, 0x9a, 0xe7, 0x7d, 0xe6, 0x9d, 0x0e,
	0x4c, 0x1a, 0x32, 0x2d, 0xab, 0xa6, 0x75, 0xcf, 0xf6, 0xa4, 0x2e, 0x95, 0x65, 0x6a, 0x09, 0xcb,
	0x9e, 0xce, 0x12, 0xe1, 0xec, 0x34, 0x47, 0x61, 0xf6, 0xf8, 0x4f, 0x0f, 0x4c, 0x67, 0x1b, 0xf1,
	0x62, 0x0f, 0x37, 0xdb, 0x93, 0xba, 0x1c, 0xcd, 0x01, 0x9f, 0x60, 0xe8, 0x0b, 0x35, 0x4f, 0xb3,
	0x79, 0xb6, 0x1a, 0xd7, 0x0f, 0x55, 0x3f, 0x52, 0x7d, 0x38, 0xcd, 0xb2, 0x8b, 0x71, 0x09, 0x85,
	0xfb, 0x56, 0x56, 0x4f, 0x07, 0xf3, 0x6c, 0x75, 0x5f, 0x8b, 0xc4, 0xdb, 0x79, 0x2e, 0x63, 0xbc,
	0xd8, 0x43, 0xbe, 0x51, 0xbf, 0x1a, 0x97, 0x90, 0xfb, 0xc9, 0xae, 0x16, 0x13, 0xbd, 0x5b, 0x2d,
	0x43, 0x8e, 0x6b, 0x28, 0xc2, 0xd7, 0x42, 0xef, 0xb8, 0x9e, 0x24, 0xe2, 0xc6, 0xf3, 0x37, 0xf3,
	0x45, 0x32, 0x2a, 0xeb, 0x57, 0x28, 0xc2, 0x2e, 0xbc, 0x83, 0x32, 0x3c, 0xde, 0xc9, 0x68, 0x71,
	0x85, 0x23, 0xc8, 0x25, 0x35, 0x3f, 0x22, 0xc3, 0x12, 0x8a, 0xad, 0xb2, 0x9a, 0xc5, 0x00, 0x6f,
	0x61, 0xb4, 0x6b, 0x8e, 0xce, 0x11, 0x3b, 0x71, 0xfd, 0x39, 0x0c, 0x97, 0xbf, 0xfc, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x4d, 0x8a, 0x3d, 0xde, 0x49, 0x01, 0x00, 0x00,
}
