// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/user.proto

package contracts

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a7e9b27c0430d2, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserEvent struct {
	User                 *User     `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Type                 EventType `protobuf:"varint,2,opt,name=Type,proto3,enum=contracts.EventType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserEvent) Reset()         { *m = UserEvent{} }
func (m *UserEvent) String() string { return proto.CompactTextString(m) }
func (*UserEvent) ProtoMessage()    {}
func (*UserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a7e9b27c0430d2, []int{1}
}

func (m *UserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEvent.Unmarshal(m, b)
}
func (m *UserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEvent.Marshal(b, m, deterministic)
}
func (m *UserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEvent.Merge(m, src)
}
func (m *UserEvent) XXX_Size() int {
	return xxx_messageInfo_UserEvent.Size(m)
}
func (m *UserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserEvent proto.InternalMessageInfo

func (m *UserEvent) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserEvent) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EventNone
}

type ReceptionResponse struct {
	Acknowledged         bool     `protobuf:"varint,1,opt,name=Acknowledged,proto3" json:"Acknowledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceptionResponse) Reset()         { *m = ReceptionResponse{} }
func (m *ReceptionResponse) String() string { return proto.CompactTextString(m) }
func (*ReceptionResponse) ProtoMessage()    {}
func (*ReceptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2a7e9b27c0430d2, []int{2}
}

func (m *ReceptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceptionResponse.Unmarshal(m, b)
}
func (m *ReceptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceptionResponse.Marshal(b, m, deterministic)
}
func (m *ReceptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceptionResponse.Merge(m, src)
}
func (m *ReceptionResponse) XXX_Size() int {
	return xxx_messageInfo_ReceptionResponse.Size(m)
}
func (m *ReceptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceptionResponse proto.InternalMessageInfo

func (m *ReceptionResponse) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "contracts.User")
	proto.RegisterType((*UserEvent)(nil), "contracts.UserEvent")
	proto.RegisterType((*ReceptionResponse)(nil), "contracts.ReceptionResponse")
}

func init() { proto.RegisterFile("contracts/user.proto", fileDescriptor_a2a7e9b27c0430d2) }

var fileDescriptor_a2a7e9b27c0430d2 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0x29, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x84, 0x8b, 0x4a, 0x21, 0x29, 0x48, 0xcd, 0x2b, 0xcd, 0x85, 0x28, 0x50, 0xd2, 0xe2,
	0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x12, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x02,
	0x8b, 0x80, 0xd9, 0x4a, 0x51, 0x5c, 0x9c, 0x20, 0xb5, 0xae, 0x65, 0xa9, 0x79, 0x25, 0x42, 0xca,
	0x10, 0x8d, 0x60, 0x2d, 0xdc, 0x46, 0xfc, 0x7a, 0x70, 0xd3, 0xf5, 0x40, 0xc2, 0x41, 0x10, 0x53,
	0x35, 0xb8, 0x58, 0x42, 0x2a, 0x0b, 0x20, 0xa6, 0xf0, 0x19, 0x89, 0x20, 0x29, 0x02, 0x1b, 0x02,
	0x92, 0x0b, 0x02, 0xab, 0x50, 0x32, 0xe7, 0x12, 0x0c, 0x4a, 0x4d, 0x4e, 0x2d, 0x28, 0xc9, 0xcc,
	0xcf, 0x0b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe2, 0xe2, 0x71, 0x4c, 0xce,
	0xce, 0xcb, 0x2f, 0xcf, 0x49, 0x4d, 0x49, 0x4f, 0x4d, 0x01, 0xdb, 0xc5, 0x11, 0x84, 0x22, 0x66,
	0xe4, 0xc7, 0xc5, 0x0b, 0xb6, 0x10, 0xa6, 0x59, 0xc8, 0x96, 0x8b, 0xd5, 0x39, 0x23, 0x35, 0x39,
	0x5b, 0x48, 0x04, 0xcd, 0x4d, 0x60, 0x2b, 0xa5, 0x64, 0x90, 0x44, 0x31, 0x6c, 0x54, 0x62, 0x48,
	0x62, 0x03, 0x87, 0x8b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xc6, 0xf8, 0x35, 0x50, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserReceptionClient is the client API for UserReception service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserReceptionClient interface {
	// User check
	Check(ctx context.Context, in *UserEvent, opts ...grpc.CallOption) (*ReceptionResponse, error)
}

type userReceptionClient struct {
	cc *grpc.ClientConn
}

func NewUserReceptionClient(cc *grpc.ClientConn) UserReceptionClient {
	return &userReceptionClient{cc}
}

func (c *userReceptionClient) Check(ctx context.Context, in *UserEvent, opts ...grpc.CallOption) (*ReceptionResponse, error) {
	out := new(ReceptionResponse)
	err := c.cc.Invoke(ctx, "/contracts.UserReception/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserReceptionServer is the server API for UserReception service.
type UserReceptionServer interface {
	// User check
	Check(context.Context, *UserEvent) (*ReceptionResponse, error)
}

// UnimplementedUserReceptionServer can be embedded to have forward compatible implementations.
type UnimplementedUserReceptionServer struct {
}

func (*UnimplementedUserReceptionServer) Check(ctx context.Context, req *UserEvent) (*ReceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

func RegisterUserReceptionServer(s *grpc.Server, srv UserReceptionServer) {
	s.RegisterService(&_UserReception_serviceDesc, srv)
}

func _UserReception_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserReceptionServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contracts.UserReception/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserReceptionServer).Check(ctx, req.(*UserEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserReception_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contracts.UserReception",
	HandlerType: (*UserReceptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _UserReception_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contracts/user.proto",
}
