package main

import (
	"fmt"
	"log"

	"github.com/iris-contrib/swagger"
	"github.com/iris-contrib/swagger/swaggerFiles"
	"github.com/kataras/iris"

	_ "github.com/vincent-scw/gframe/player_reception_svc/docs" // docs is generated by Swag CLI
	"github.com/vincent-scw/gframe/player_reception_svc/kafka"
)

func main() {
	app := iris.Default()

	app.Get("health", func(ctx iris.Context) {
		ctx.Text("I am good.")
	})

	app.Post("message", func(ctx iris.Context) {
		var messages []kafka.TextMessage
		err := ctx.ReadJSON(&messages)
		if err != nil {
			log.Fatalln(err)
			ctx.StatusCode(iris.StatusBadRequest)
		}

		p := kafka.NewProducer()
		defer p.Dispose()
		for i := 0; i < len(messages); i++ {
			messages[i].Key = fmt.Sprintf("address-%s", ctx.RemoteAddr())
		}
		p.EmitMulti(messages)
	})

	config := &swagger.Config{
		URL: "http://localhost:8080/swagger/doc.json",
	}
	app.Get("/swagger/{any:path}", swagger.CustomWrapHandler(config, swaggerFiles.Handler))

	fmt.Println("Start player api...")
	app.Run(iris.Addr(":8080"))
}
